<?php require_once ("template/header.phtml")?>

<body role="document">

<div id="controlArea">
    <canvas id="canvas">
        <div id="Details">
            <p id="FPS"></p>
        </div>
    </canvas>
</div>

<!-- Pass the model name to JavaScript -->
<script>
    var modelFile = "<?php echo htmlspecialchars($model, ENT_QUOTES, 'UTF-8'); ?>";
</script>

<script src="js/index.js" type="module"></script>

<?php require_once "template/footer.phtml" ?>
