<?php require('template/header.phtml') ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/css/my-style.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>
<body role="document">

<div id="controlArea">

    <canvas id="canvas" >
        <div id="Details">
            <p id="FPS"></p>
        </div>
    </canvas>

</div>


<script src="js/index.js" type="module"></script>

<!-- Spline script -->
<script type="module" src="https://unpkg.com/@splinetool/viewer@1.9.48/build/spline-viewer.js"></script>

<div id="splineContainer" style="width: 100%; height: 500px; border: 1px solid #ccc;">
    <spline-viewer url="https://prod.spline.design/ve77TZqSvj6qDrEq/scene.splinecode"></spline-viewer>
</div>

<?php require('template/footer.phtml')?>
