<?php require('template/header.phtml') ?>

<body>
<div id="progress-container">
    <dialog open id="progress-dialog">
        <p>
            <label for="progress-indicator">Loading scene...</label>
        </p>
        <progress max="100" id="progress-indicator"></progress>
    </dialog>
</div>

<canvas id="canvas"></canvas>
<script src="index.js" type="module"></script>
</body>

<?php require('template/footer.phtml') ?>
