<?php require_once ("template/header.phtml")?>


<main class="main-content">
    <div class="container">
        <h1 class="page-title">3D Models Gallery</h1>
        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
                <?php foreach($images as $image): ?>
                    <div class="swiper-slide">
                        <div class="card">
                            <div class="card-image">
                                <img class="card-img"
                                     src="<?= htmlspecialchars($image['src']) ?>"
                                     alt="<?= htmlspecialchars($image['title']) ?>" />
                            </div>
                            <div class="card-content">
                                <h2 class="card-title"><?= htmlspecialchars($image['title']) ?></h2>
                                <p class="card-description"><?= $image['description'] ?></p>
                                <a href="<?= htmlspecialchars($image['url']) ?>" class="card-button" id="click">View The Model</a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>
</main>


<!-- Swiper JS (CDN) -->
<script src="https://unpkg.com/swiper@9/swiper-bundle.min.js"></script>
<!-- Custom JS -->
<script src="/js/script.js"></script>


<?php require_once "template/footer.phtml" ?>
