<?php require('template/header.phtml') ?>


    <p style="color: red" id="errorMessage"></p>
    <div class="d-flex justify-content-center align-items-center" style="height: 15vh; margin: 0;">
        <div class="text-center">
            <input type="file" class="form-control visually-hidden" id="splatInput" accept=".splat">
            <label class="btn btn-primary" for="splatInput">Upload Splat File</label>
            <p style="color: red" id="errorMessage" class="mt-2"></p>
        </div>
    </div>

    <div id="controlArea">

        <canvas id="canvas" >
            <div id="Details">
                <p id="FPS"></p>
            </div>
        </canvas>

    </div>

    <script src="js/upload.js" type="module"></script>

<?php require('template/footer.phtml')?>