<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Ensures proper rendering and touch zooming on mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>3D Gaussian Splatting</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
        crossorigin="anonymous"
    >
    <link rel="stylesheet" href="/css/my_style.css">
</head>

<body>



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- Brand Name or Logo -->
        <a class="navbar-brand" href="index.php">3D Gaussian Splatting</a>

        <!-- Toggler button for small screens -->
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible Menu Items -->
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">


            <!-- Right-aligned links -->
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="#" class="nav-link text-light">About</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link text-light">Contact</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link text-light">Upload</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Bootstrap JS Bundle with Popper -->
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3MB0H7yY3F5mH+fax/Q65/b4BO8e9QQ+7GwAv4mEc5i5cwH5US5UiJ5g7rsz68f"
    crossorigin="anonymous">
</script>

</body>
</html>
